# ui_camera_picker.py intial structure generated by ChatGPT
import json
import pathlib
import tkinter as tk
from tkinter import ttk, messagebox

STORE_PATH = pathlib.Path("camera_source.json")

def _load_last():
    try:
        if STORE_PATH.exists():
            return json.loads(STORE_PATH.read_text()).get("source")
    except Exception:
        pass
    return None

def _save_last(source):
    try:
        STORE_PATH.write_text(json.dumps({"source": source}, indent=2))
    except Exception:
        pass

def pick_camera_source(title="Select Camera Source", enable_test=True):
    """
    Shows a small modal UI and returns either:
      - int (webcam index), or
      - str (RTSP URL)
    Returns None if the user cancels.
    """
    root = tk.Tk()
    root.title(title)
    root.resizable(False, False)

    # --- State
    mode = tk.StringVar(value="webcam")
    webcam_index = tk.StringVar(value="0")
    rtsp_url = tk.StringVar(value="rtsp://user:pass@192.168.1.90:554/axis-media/media.amp")

    last = _load_last()
    if last is not None:
        if isinstance(last, int) or (isinstance(last, str) and last.isdigit()):
            mode.set("webcam")
            webcam_index.set(str(last))
        else:
            mode.set("rtsp")
            rtsp_url.set(str(last))

    # --- Layout
    pad = {"padx": 10, "pady": 6}
    frm = ttk.Frame(root, padding=12)
    frm.grid(row=0, column=0)

    ttk.Label(frm, text="Choose source type:").grid(row=0, column=0, sticky="w", **pad)
    ttk.Radiobutton(frm, text="Webcam (index)", variable=mode, value="webcam").grid(row=1, column=0, sticky="w", **pad)
    ttk.Radiobutton(frm, text="RTSP URL",       variable=mode, value="rtsp").grid(row=2, column=0, sticky="w", **pad)

    ttk.Label(frm, text="Index:").grid(row=1, column=1, sticky="e", **pad)
    e_idx = ttk.Entry(frm, textvariable=webcam_index, width=8)
    e_idx.grid(row=1, column=2, sticky="w", **pad)

    ttk.Label(frm, text="URL:").grid(row=2, column=1, sticky="e", **pad)
    e_url = ttk.Entry(frm, textvariable=rtsp_url, width=48)
    e_url.grid(row=2, column=2, sticky="w", **pad)

    # --- Actions
    def do_ok():
        m = mode.get()
        if m == "webcam":
            val = webcam_index.get().strip()
            if not val.isdigit():
                messagebox.showerror("Invalid value", "Webcam index must be an integer (e.g., 0).")
                return
            root.result = int(val)
        else:
            url = rtsp_url.get().strip()
            if not (url.startswith("rtsp://") and "@" in url):
                if not messagebox.askyesno(
                    "Confirm URL",
                    "The URL doesn't look like a typical RTSP URL.\nContinue anyway?"
                ):
                    return
            root.result = url
        _save_last(root.result)
        root.destroy()

    def do_cancel():
        root.result = None
        root.destroy()

    def do_test():
        try:
            import cv2
        except Exception:
            messagebox.showerror("OpenCV not found", "Install opencv-python to test streams.")
            return
        # get candidate source (without saving)
        src = int(webcam_index.get()) if mode.get()=="webcam" and webcam_index.get().isdigit() else rtsp_url.get().strip()
        try:
            # Prefer FFMPEG backend for RTSP
            cap = cv2.VideoCapture(src, cv2.CAP_FFMPEG) if isinstance(src, str) else cv2.VideoCapture(src)
            ok, frame = cap.read()
            cap.release()
            if not ok or frame is None:
                messagebox.showerror("Test failed", "Could not read a frame from the selected source.")
            else:
                h, w = frame.shape[:2]
                messagebox.showinfo("Test OK", f"Got a frame: {w}x{h}")
        except Exception as e:
            messagebox.showerror("Test error", str(e))

    btns = ttk.Frame(frm)
    btns.grid(row=3, column=0, columnspan=3, sticky="e", padx=10, pady=10)

    if enable_test:
        ttk.Button(btns, text="Test", command=do_test).grid(row=0, column=0, padx=6)
    ttk.Button(btns, text="Cancel", command=do_cancel).grid(row=0, column=1, padx=6)
    ttk.Button(btns, text="OK", command=do_ok).grid(row=0, column=2)

    # Focus friendly defaults
    (e_idx if mode.get()=="webcam" else e_url).focus_set()

    # Center window
    root.update_idletasks()
    w, h = root.winfo_width(), root.winfo_height()
    sw, sh = root.winfo_screenwidth(), root.winfo_screenheight()
    root.geometry(f"+{(sw-w)//2}+{(sh-h)//2}")

    root.result = None
    root.mainloop()
    return root.result
